### ISSUE TITLE
Change function name to gh instead of npmPlugin

### ISSUE THREAD

**Issue by seanc** [jamen/hmu-gh#1]
while rewriting tests for hmu-request-resolve i ran into an issue where the requests' functions are named the same and are causing issues.

**Comment by jamen** [comment]
with `hmu-core`, it shouldn't matter what the functions are named.

anyways, plugins are mostly different with the new `hmu-core` anyways.  I (or we) should just rewrite them all.

New plugins are like this:

```js
module.exports = function (input, options, done) {

}
```



Call done with `done(err, result)`, with `result` being some map/reduce of `input` normally.
